vendor: bump prometheus/client_golang v0.9.4
full diff: https://github.com/prometheus/client_golang/compare/f4fb1b73fb099f396a7f0036bf86aa8def4ed823...v0.9.4

version v0.9.0 is the minimum tagged version to work with go-metrics v0.0.1,
as it depends on `prometheus.Observer`:

    vendor/github.com/docker/go-metrics/timer.go:39:4: undefined: prometheus.Observer

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>